version: 2
updates:
    # NuGet packages
    - package-ecosystem: "nuget"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "wednesday"
      open-pull-requests-limit: 5
      groups:
          dotnet:
              patterns:
                  - "*"
