using System.Collections.Generic;

namespace Affected.Cli
{
    /// <summary>
    /// Defines the strategy for generating outputs.
    /// </summary>
    public interface IOutputStrategy
    {
        /// <summary>
        /// Gets all outputs generated by the strategy.
        /// </summary>
        IEnumerable<IOutput> GetOutputs();
    }
}
