//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetAffected.Tasks.Tests.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestProjectScenarios {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestProjectScenarios() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DotnetAffected.Tasks.Tests.Resources.TestProjectScenarios", typeof(TestProjectScenarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DirectoryBuildProps {
            get {
                return ResourceManager.GetString("DirectoryBuildProps", resourceCulture);
            }
        }
        
        internal static string CiProps {
            get {
                return ResourceManager.GetString("CiProps", resourceCulture);
            }
        }
        
        internal static string AffectedFilterClass {
            get {
                return ResourceManager.GetString("AffectedFilterClass", resourceCulture);
            }
        }
        
        internal static string AssumeChanges {
            get {
                return ResourceManager.GetString("AssumeChanges", resourceCulture);
            }
        }
        
        internal static string GitBetweenCommits {
            get {
                return ResourceManager.GetString("GitBetweenCommits", resourceCulture);
            }
        }
    }
}
